name:                krapu
version:             0.1.0.0
github:              "atarv/krapu"
license:             BSD3
author:              "Aleksi Tarvainen"
maintainer:          "a.aleksi.tarvainen@student.jyu.fi"
copyright:           "Aleksi Tarvainen"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/atarv/krapu#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  krapu-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - krapu

tests:
  krapu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - krapu
